update:
	./fetch KBFI
	./fetch KBLI
	./fetch KPAE
	./fetch KSEA
	./fetch KSFO
	./fetch ZGOW
	./fetch EGLC
	./fetch EGGD
	./fetch KNYC
	./fetch LIMC
	./fetch EHRD
	./fetch VABB
	./fetch SAWH
	./fetch ENQA
